version: '3.3'
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: shared-mysql
      PMA_PORT: 3306
    networks:
      - partdb-net

networks:
  partdb-net:
    external: true
